# -*- coding: utf-8 -*-
"""Cozy_again.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dyVyplJSEyMWkbQKyQmxzvA0ESZMz14E
"""

import pandas as pd
import numpy as np
import re

df_data = pd.read_csv('/content/Dataset.csv')
df_brand = pd.read_csv('Brandlist.csv')

"""#Dim Master Brand."""

import re
# LÀM SẠCH CỘT BRAND_ID
df_brand['Brand_Id'] = df_brand['Brand_Id'].astype(str)
df_brand['Brand_Id'] = df_brand['Brand_Id'].str.replace(r'\s+', '', regex=True)
df_brand['Brand_Id'] = df_brand['Brand_Id'].astype(int)
# LÀM SẠCH CỘT BRAND_NAME ---
df_brand['Brand_Name'] = df_brand['Brand_Name'].astype(str)
df_brand['Brand_Name'] = df_brand['Brand_Name'].str.strip()
df_brand['Brand_Name'] = df_brand['Brand_Name'].str.replace('–', '-', regex=False)
df_brand['Brand_Name'] = df_brand['Brand_Name'].str.replace(r'\s+', ' ', regex=True)

# Thêm cột Master_Id và Master_Brand
def get_master_brand(name):
    name_lower = name.lower()
    if 'cozy' in name_lower:
        return 400,'Cozy'
    elif 'c2' in name_lower:
        return 100, 'C2'
    elif 'không độ' in name_lower or 'khong do' in name_lower:
        return 300,'Không Độ'
    elif 'tea plus' in name_lower or 'ô long' in name_lower:
        return 200,'Olong Tea Plus'
    elif 'boncha' in name_lower:
        return 500,'Boncha'
    elif 'dr. thanh' in name_lower:
        return 600,'Dr. Thanh'
    else:
        return 700,'Khác'
df_brand['Master_Id'], df_brand['Master_Brand'] = zip(*df_brand['Brand_Name'].apply(get_master_brand))
df_brand['Master_Id'] = df_brand['Master_Id'].astype(int)

"""Tạo bảng Dim_Master_Brand"""

dim_master_brand = df_brand[['Master_Id', 'Master_Brand']].drop_duplicates().reset_index(drop=True)
dim_master_brand = dim_master_brand.sort_values(by='Master_Id').reset_index(drop=True)

dim_master_brand

dim_master_brand.to_csv('Dim Master Brand.csv', index=False, encoding='utf-8-sig')

"""#Làm sạch df_data"""

columns_to_drop = [
    'S2.Category used in P4W_Powder/bag tea','S2.Category used in P4W_Juice (freshly made)',
    'S2.Category used in P4W_Juice (powder)', 'S2.Category used in P4W_Branded water bottle (5 - 20 liter)',
    'S2.Category used in P4W_Unbranded tea (ice tea, hot tea, milk tea, lemon tea, …)',
    'S2.Category used in P4W_Unbranded home-made soya milk',
    'S2.Category used in P4W_Branded bottled/canned/packaged/boxed soya milk',
    'S2.Category used in P4W_Cow milk',
    'S2.Category used in P4W_Drinking yogurt',
    'S2.Category used in P4W_Traditional drink (unbranded)',
    'S2.Category used in P4W_Carbonated soft drink (strawberry flavour)',
    'S2.Category used in P4W_Coffee', 'S2.Category used in P4W_Non-flavoured natural mineral water (less than 1.5 liter)',
    'S2.Category used in P4W_Non-flavoured natural mineral water (5 - 20 liter)',
    'S2.Category used in P4W_Branded bottled/ canned/ packaged/ boxed green bean milk',
    'S2.Category used in P4W_Branded bottled/ canned/ packaged/ boxed nut milk (exculding soya/ green bean milk)',
    'S2.Category used in P4W_None'
]
df_data = df_data.drop(columns=columns_to_drop, errors='ignore')
display(df_data.head())

names_of_columns = df_data.columns.tolist()
print(names_of_columns)

# Clean cột Income
df_data['D4.Income'] = df_data['D4.Income'].astype(str)
# Xóa chữ "VND"
df_data['D4.Income'] = df_data['D4.Income'].str.replace(r'VND', '', regex=True, flags=re.IGNORECASE)
# Chuẩn hóa dấu gạch ngang dài (–) thành dấu gạch ngang chuẩn (-)
df_data['D4.Income'] = df_data['D4.Income'].str.replace('–', '-')
# Dọn sạch dấu xuống dòng (\n) và các khoảng trắng thừa, biến chúng thành 1 khoảng trắng duy nhất
df_data['D4.Income'] = df_data['D4.Income'].str.strip().str.replace(r'\s+', ' ', regex=True)
df_data['D4.Income'] = df_data['D4.Income'].str.replace(r'\s*-\s*', ' - ', regex=True)
df_data['D4.Income'] = df_data['D4.Income'].str.strip()

# Clean cột Age
# Chuyển cột D3.Age về dạng chuỗi (string)
df_data['D3.Age'] = df_data['D3.Age'].astype(str)
# 2. Xóa chữ "y.o." hoặc "y.o" (không phân biệt hoa thường)
df_data['D3.Age'] = df_data['D3.Age'].str.replace(r'y\.o\.?', '', regex=True, flags=re.IGNORECASE)
# 3. Làm sạch các dấu xuống dòng (\n) hoặc khoảng trắng thừa còn sót lại trong ô dữ liệu
df_data['D3.Age'] = df_data['D3.Age'].str.strip().str.replace(r'\s+', ' ', regex=True)

# Drop các cột không có thông tin
trash_patterns = [r'98', r'99', r'dk/na', r'none']
cols_to_drop = [
    col for col in df_data.columns
    if any(re.search(pattern, col.lower()) for pattern in trash_patterns)
]
df_data = df_data.drop(columns=cols_to_drop)

df_data.rename(columns={'S3b_ Bạn uống trà uống liền (đóng chai/lon/hộp) với mức độ thường xuyên như thế nào trong 4 tuần qua?{#SA_text_label}': 'S3b_Frequency'}, inplace=True)

survey_cols = df_data.columns[3:]
for col in survey_cols:
    df_data[col] = df_data[col].astype(str).str.strip().str.capitalize()
    # Chuẩn hóa 'Yes' = 1, 'No' = 0 và giữ nguyên các giá trị khác
    df_data[col] = df_data[col].apply(lambda x: 1 if x == 'Yes' else (0 if x == 'No' else x))

df_data = df_data.replace("#null!", pd.NA)

df_data.head()

df_data.describe()

"""#Dim Respondent"""

dim_respondent = df_data[['Serial number', 'Wave', 'Region','D4.Income','D2.Gender','D3.Age','D6.Occupation','D7.Educational level']]
dim_respondent = dim_respondent.drop_duplicates()

#dim_respondent.to_csv('Dim_Respondent.csv', index=False, encoding='utf-8-sig')

"""#Fact Funnel"""

vlookup_dict_brand_to_master_id = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))

df_tom_answers = df_data[['Serial number', 'Wave', 'Q1.TOM']].copy()
df_tom_answers['TOM_Master_Id_Answer'] = df_tom_answers['Q1.TOM'].apply(
    lambda val: vlookup_dict_brand_to_master_id.get(re.sub(r'\s+', ' ', str(val).strip().replace('–', '-').lower()), -1)
)

df_tom_answers

df_base_for_cross_join = df_data[['Serial number', 'Wave']].drop_duplicates().copy()
df_base_for_cross_join['key'] = 1

# Lấy các Master_Id từ dim_master_brand
dim_master_brand_for_merge = dim_master_brand[['Master_Id']].copy()
dim_master_brand_for_merge['key'] = 1

# Thực hiện phép nhân chéo (cross-join)
fact_funnel = pd.merge(df_base_for_cross_join, dim_master_brand_for_merge, on='key').drop(columns=['key'])

fact_funnel.head()

# Ghép fact_funnel với df_tom_answers để có Master_Id thực tế của câu trả lời TOM
fact_funnel = pd.merge(fact_funnel, df_tom_answers[['Serial number', 'Wave', 'TOM_Master_Id_Answer']],
                        on=['Serial number', 'Wave'], how='left')

# Tạo cột 'TOM' (1 nếu Master_Id của dòng bằng TOM_Master_Id_Answer, ngược lại là 0)
fact_funnel['TOM'] = (fact_funnel['Master_Id'] == fact_funnel['TOM_Master_Id_Answer']).astype(int)

# Loại bỏ cột tạm thời TOM_Master_Id_Answer để giữ bảng gọn gàng
fact_funnel = fact_funnel.drop(columns=['TOM_Master_Id_Answer'])

# Hiển thị kết quả
fact_funnel

"""## **Xử lý Cột BUMO**

"""

# Bước 1: Tạo BUMO_Master_Id_Answer

# Tạo DataFrame chứa câu trả lời BUMO và ánh xạ sang Master_Id thực tế
df_bumo_answers = df_data[['Serial number', 'Wave', 'Q5.Bumo']].copy()
df_bumo_answers['BUMO_Master_Id_Answer'] = df_bumo_answers['Q5.Bumo'].apply(
    lambda val: vlookup_dict_brand_to_master_id.get(re.sub(r'\s+', ' ', str(val).strip().replace('–', '-').lower()), -1)
)

df_bumo_answers

# Ghép fact_funnel với df_bumo_answers để có Master_Id thực tế của câu trả lời BUMO
fact_funnel = pd.merge(fact_funnel, df_bumo_answers[['Serial number', 'Wave', 'BUMO_Master_Id_Answer']],
                        on=['Serial number', 'Wave'], how='left')

# Tạo cột 'BUMO' (1 nếu Master_Id của dòng bằng BUMO_Master_Id_Answer, ngược lại là 0)
fact_funnel['BUMO'] = (fact_funnel['Master_Id'] == fact_funnel['BUMO_Master_Id_Answer']).astype(int)

# Loại bỏ cột tạm thời BUMO_Master_Id_Answer
fact_funnel = fact_funnel.drop(columns=['BUMO_Master_Id_Answer'])

# Hiển thị kết quả
fact_funnel

# Bước 1: Lấy câu trả lời Previous BUMO, map sang Master_Id (dùng đúng cách
# chuẩn hoá text giống hệt BUMO hiện tại để đảm bảo nhất quán)
df_previous_bumo = df_data[['Serial number', 'Wave', 'Q7. Previous BUMO']].copy()
df_previous_bumo['Previous_Master_Id_Answer'] = df_previous_bumo['Q7. Previous BUMO'].apply(
    lambda val: vlookup_dict_brand_to_master_id.get(
        re.sub(r'\s+', ' ', str(val).strip().replace('–', '-').lower()), np.nan
    ) if pd.notna(val) else np.nan
)

# Bước 2: Ghép vào fact_funnel (chỉ theo Serial + Wave, không theo Master_Id
# — vì Previous BUMO là thuộc tính của NGƯỜI, không phải của từng brand row)
fact_funnel = pd.merge(
    fact_funnel,
    df_previous_bumo[['Serial number', 'Wave', 'Previous_Master_Id_Answer']],
    on=['Serial number', 'Wave'], how='left'
)

# Bước 3: CHỈ điền Previous_Master_Id vào đúng dòng đang là BUMO=1 của người đó
# (tránh lặp lại sai nghĩa trên cả 7 dòng brand — Previous BUMO chỉ có ý nghĩa
# gắn với dòng đại diện cho brand HIỆN TẠI của họ)
fact_funnel['Previous_Master_Id'] = np.where(
    fact_funnel['BUMO'] == 1,
    fact_funnel['Previous_Master_Id_Answer'],
    np.nan
)
fact_funnel = fact_funnel.drop(columns=['Previous_Master_Id_Answer'])

# Bước 4: Map Master_Id -> tên Master_Brand (dùng lại dim_master_brand có sẵn)
master_brand_lookup = dict(zip(dim_master_brand['Master_Id'], dim_master_brand['Master_Brand']))
fact_funnel['Previous_Master_Brand'] = fact_funnel['Previous_Master_Id'].map(master_brand_lookup)

# Bước 5: Gắn nhãn Switch_Status — chỉ có giá trị ở đúng dòng BUMO=1
fact_funnel['Switch_Status'] = np.select(
    condlist=[
        fact_funnel['BUMO'] != 1,                                                            # không phải dòng BUMO -> để trống
        fact_funnel['Previous_Master_Id'].isna(),                                             # BUMO=1 nhưng không có Previous -> chưa xác định
        fact_funnel['Master_Id'] == fact_funnel['Previous_Master_Id'],                        # BUMO=1 và giống Previous -> trung thành
    ],
    choicelist=[
        None,
        'No Previous Data',
        'Loyal',
    ],
    default='Switched'   # BUMO=1, có Previous, và khác Master_Id hiện tại -> đã đổi brand
)

# Kiểm tra nhanh
print(fact_funnel[fact_funnel['BUMO']==1]['Switch_Status'].value_counts())

"""## **Xử lý các cột Q3. P3M (Used Past 3 Months)**


"""

# Bước 1 & 2: Xác định và Unpivot (Melt) các cột Q3. P3M

# Tìm tất cả các cột P3M
p3m_cols = [col for col in df_data.columns if col.startswith('Q3. P3M _')]

# Unpivot (melt) các cột P3M
df_p3m_melted = df_data[['Serial number', 'Wave'] + p3m_cols].melt(
    id_vars=['Serial number', 'Wave'],
    value_vars=p3m_cols,
    var_name='P3M_Brand_Col',
    value_name='P3M_Response'
)

df_p3m_melted["P3M_Brand_Col"] = df_p3m_melted["P3M_Brand_Col"].str.replace(
    "Q3. P3M _", "", regex=False
)
df_p3m_melted

vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))

# Nếu bảng danh mục có cột Master_Brand, gộp thêm vào để tra cứu cho an toàn tuyệt đối
if 'Master_Brand' in df_brand.columns:
    vlookup_dict.update(dict(zip(df_brand['Master_Brand'].str.lower(), df_brand['Master_Id'])))

# 2. Tiến hành VLOOKUP điền cột Master_Id vào bảng df_p3m_melted
# .strip() và .lower() để làm sạch chuỗi đem đi dò
df_p3m_melted['Master_Id'] = df_p3m_melted['P3M_Brand_Col'].astype(str).str.strip().str.lower().map(vlookup_dict)

# Xem thử kết quả bảng sau khi được điền Master_Id
df_p3m_melted

# Lấy df_p3m_melted đã được xử lý từ các bước trước (cell qJhY94PT7sdR, xEwLh-f_B2XJ, eWfdfdEoC4Jx)
# df_p3m_melted hiện tại đã có các cột: 'Serial number', 'Wave', 'P3M_Brand_Col', 'P3M_Response', 'Master_Id'

# 1. Filter df_p3m_melted for relevant responses and valid Master_Id
df_p3m_processed_for_merge = df_p3m_melted[
    (df_p3m_melted['P3M_Response'] == 1) & # Chỉ giữ lại các dòng có phản hồi là 'Yes' (đã được chuyển thành 1)
    (df_p3m_melted['Master_Id'].notna()) # Chỉ giữ lại các dòng mà Master_Id đã được ánh xạ thành công
].copy()

# 2. Prepare df_p3m_flags for merging into fact_funnel
# Đổi tên cột 'Serial number' thành 'Serial' để khớp với 'fact_funnel'
df_p3m_flags_final = df_p3m_processed_for_merge[['Serial number', 'Wave', 'Master_Id']].copy()
df_p3m_flags_final = df_p3m_flags_final.drop_duplicates()

# 3. Tạo một cột cờ tạm thời 'P3M_Flag_Temp' để đánh dấu các mục P3M được chọn
df_p3m_flags_final['P3M_Flag_Temp'] = 1

# 4. Thực hiện merge với fact_funnel để cập nhật cột P3M
# fact_funnel hiện tại đã có các cột: 'Serial', 'Wave', 'Master_Id', 'TOM', 'BUMO' (và có thể là một cột 'P3M' cũ)

# Nếu cột 'P3M_Flag_Temp' đã tồn tại trong fact_funnel (từ các lần chạy trước đó), hãy xóa nó đi trước khi merge lại
if 'P3M_Flag_Temp' in fact_funnel.columns:
    fact_funnel = fact_funnel.drop(columns=['P3M_Flag_Temp'])

# Nếu cột 'P3M' đã tồn tại trong fact_funnel (từ các lần chạy trước đó), hãy xóa nó đi trước khi merge lại
if 'P3M' in fact_funnel.columns:
    fact_funnel = fact_funnel.drop(columns=['P3M'])

fact_funnel = pd.merge(
    fact_funnel,
    df_p3m_flags_final,
    on=['Serial number', 'Wave', 'Master_Id'],
    how='left' # Sử dụng left merge để giữ lại tất cả các dòng của fact_funnel
)

# 5. Điền 0 cho các giá trị NaN trong 'P3M_Flag_Temp' và chuyển sang kiểu int cho cột 'P3M' cuối cùng
fact_funnel['P3M'] = fact_funnel['P3M_Flag_Temp'].fillna(0).astype(int)

# 6. Xóa cột tạm thời 'P3M_Flag_Temp'
fact_funnel = fact_funnel.drop(columns=['P3M_Flag_Temp'])

# Hiển thị 10 dòng đầu của fact_funnel để kiểm tra cột P3M
print(fact_funnel.info())
fact_funnel

fact_funnel.describe()

"""##**'Q4Q8.BRAND CONSIDERATION SET_**"""

# Gom việc tạo dict từ Brand_Name và Master_Brand lại làm một bằng cách dùng toán tử | (Python 3.9+)
vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))
if 'Master_Brand' in df_brand.columns:
    vlookup_dict |= dict(zip(df_brand['Master_Brand'].str.lower(), df_brand['Master_Id']))


# --- 2. UNPIVOT (MELT) VÀ XỬ LÝ DỮ LIỆU CONSIDERATION ---
# Tìm các cột thỏa mãn điều kiện
consideration_cols = [col for col in df_data.columns if col.startswith('Q4Q8.BRAND CONSIDERATION SET_')]

# Melt và xử lý chuỗi, map ID, lọc dữ liệu chỉ trong 1 block code liền mạch (Chaining)
df_consideration_flags = (
    df_data[['Serial number', 'Wave'] + consideration_cols]
    .melt(id_vars=['Serial number', 'Wave'], value_vars=consideration_cols, var_name='Consideration_cols', value_name='Consideration_Response')

    # Xử lý chuỗi: xóa prefix, strip khoảng trắng và chuyển về chữ thường để map ID
    .assign(
        Consideration_cols = lambda d: d['Consideration_cols'].str.replace("Q4Q8.BRAND CONSIDERATION SET_", "", regex=False),
        Master_Id = lambda d: d['Consideration_cols'].astype(str).str.strip().str.lower().map(vlookup_dict)
    )

    # Lọc dữ liệu: Chỉ lấy phản hồi bằng 1 (Yes) và Master_Id hợp lệ
    .query("Consideration_Response == 1 and Master_Id.notna()")

    # Chỉ giữ lại các cột cần thiết và loại bỏ trùng lặp
    [['Serial number', 'Wave', 'Master_Id']]
    .drop_duplicates()
)


# --- 3. MERGE VÀ TẠO CỘT FLAG TRONG FACT_FUNNEL ---
# Merge left với bảng fact_funnel gốc
fact_funnel = pd.merge(fact_funnel, df_consideration_flags, on=['Serial number', 'Wave', 'Master_Id'], how='left', indicator=True)

# Tận dụng cột '_merge' tự động sinh ra để tạo flag 0/1, sau đó xóa cột hệ thống này đi
fact_funnel['Consideration'] = (fact_funnel['_merge'] == 'both').astype(int)
fact_funnel = fact_funnel.drop(columns=['_merge'])


# --- 4. KIỂM TRA KẾT QUẢ ---
print(fact_funnel.info())
fact_funnel.head()

"""## **Q1.Total Spontaneous_**"""

vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))
if 'Master_Brand' in df_brand.columns:
    vlookup_dict |= dict(zip(df_brand['Master_Brand'].str.lower(), df_brand['Master_Id']))


# --- 2. UNPIVOT (MELT) VÀ XỬ LÝ DỮ LIỆU SPONTANEOUS ---
Total_Spontaneous_cols = [col for col in df_data.columns if col.startswith('Q1.Total Spontaneous_')]
brand_pattern = r"Q1\.Total Spontaneous_(.*?)(?:\s*[-–]\s*|\s+vị\s+|$)"

# Thực hiện gom toàn bộ các bước trích xuất, làm sạch chuỗi, map ID và lọc dữ liệu
df_Spontaneous_flags = (
    df_data[['Serial number', 'Wave'] + Total_Spontaneous_cols]
    .melt(id_vars=['Serial number', 'Wave'], value_vars=Total_Spontaneous_cols, var_name='Total_Spontaneous_cols', value_name='Total_Spontaneous_Response')

    # Trích xuất tên thương hiệu bằng Regex, rstrip('.1'), strip() khoảng trắng và đưa về chữ thường để map ID
    .assign(
        Brand_Clean = lambda d: d['Total_Spontaneous_cols'].str.extract(brand_pattern)[0].str.strip().str.rstrip('.1'),
        Master_Id = lambda d: d['Brand_Clean'].astype(str).str.strip().str.lower().map(vlookup_dict)
    )

    # Lọc: Chỉ giữ lại phản hồi bằng 1 và Master_Id hợp lệ
    .query("Total_Spontaneous_Response == 1 and Master_Id.notna()")

    # Giữ lại các cột định danh cốt lõi và xóa trùng lặp
    [['Serial number', 'Wave', 'Master_Id']]
    .drop_duplicates()
)


# --- 3. MERGE VÀ ĐÁNH DẤU FLAG VÀO BẢNG FACT_FUNNEL ---
# Sử dụng indicator=True để tự động tạo cột hệ thống '_merge' phân biệt dòng có khớp dữ liệu hay không
fact_funnel = pd.merge(fact_funnel, df_Spontaneous_flags, on=['Serial number', 'Wave', 'Master_Id'], how='left', indicator=True)

# Tạo cột flag chính thức (nếu khớp thành công giá trị sẽ là 'both' -> True -> 1, ngược lại là 0)
fact_funnel['Total_Spontanoues'] = (fact_funnel['_merge'] == 'both').astype(int)

# Xóa cột hệ thống '_merge'
fact_funnel = fact_funnel.drop(columns=['_merge'])


# --- 4. KIỂM TRA KẾT QUẢ ---
print(fact_funnel.info())
fact_funnel.head()

"""##**Total aided awareness_**"""

vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))
if 'Master_Brand' in df_brand.columns:
    vlookup_dict |= dict(zip(df_brand['Master_Brand'].str.lower(), df_brand['Master_Id']))


# --- 2. UNPIVOT (MELT) VÀ XỬ LÝ DỮ LIỆU AIDED AWARENESS ---
# Gom danh sách cột theo đúng tiền tố của bạn
Total_aided_awareness_cols = [col for col in df_data.columns if col.startswith('Q1Q2. Total aided awareness_')]
brand_pattern = r"Q1Q2\.\s*Total aided awareness_(.*?)(?:\s*[-–]\s*|\s+vị\s+|$)"

# Thực hiện gom toàn bộ luồng xử lý dữ liệu (Chaining)
df_aided_awareness_flags = (
    df_data[['Serial number', 'Wave'] + Total_aided_awareness_cols]
    .melt(id_vars=['Serial number', 'Wave'], value_vars=Total_aided_awareness_cols, var_name='Total_aided_awareness_cols', value_name='Total_aided_awareness_Response')

    # Trích xuất tên brand bằng Regex, rstrip('.1'), strip() và đưa về chữ thường để map ID
    .assign(
        Brand_Clean = lambda d: d['Total_aided_awareness_cols'].str.extract(brand_pattern)[0].str.strip().str.rstrip('.1'),
        Master_Id = lambda d: d['Brand_Clean'].astype(str).str.strip().str.lower().map(vlookup_dict)
    )

    # Lọc: Chỉ giữ lại các dòng phản hồi là 1 (Yes) và có Master_Id hợp lệ
    .query("Total_aided_awareness_Response == 1 and Master_Id.notna()")

    # Giữ các cột định danh quan trọng và loại bỏ dòng trùng lặp
    [['Serial number', 'Wave', 'Master_Id']]
    .drop_duplicates()
)

fact_funnel = pd.merge(fact_funnel, df_aided_awareness_flags, on=['Serial number', 'Wave', 'Master_Id'], how='left', indicator=True)

# Tạo cột flag chính thức dựa trên cột hệ thống '_merge' (Khớp thành công = 1, ngược lại = 0)
fact_funnel['Total_aided_awareness'] = (fact_funnel['_merge'] == 'both').astype(int)

# Xóa bỏ cột hệ thống '_merge' để giữ cho DataFrame sạch sẽ
fact_funnel = fact_funnel.drop(columns=['_merge'])


# --- 4. KIỂM TRA KẾT QUẢ ---
print(fact_funnel.info())
fact_funnel.head()

"""##Q4. P4W_"""

vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))
if 'Master_Brand' in df_brand.columns:
    vlookup_dict |= dict(zip(df_brand['Master_Brand'].str.lower(), df_brand['Master_Id']))


# --- 2. UNPIVOT (MELT) VÀ XỬ LÝ DỮ LIỆU AIDED AWARENESS ---
# Gom danh sách cột theo đúng tiền tố của bạn
P4W_cols = [col for col in df_data.columns if col.startswith('Q4. P4W_')]
brand_pattern = r"Q4\.\s*P4W_(.*?)(?:\s*[-–]\s*|\s+vị\s+|$)"
# Thực hiện gom toàn bộ luồng xử lý dữ liệu (Chaining)
df_P4W_flags = (
    df_data[['Serial number', 'Wave'] + P4W_cols]
    .melt(id_vars=['Serial number', 'Wave'], value_vars=P4W_cols, var_name='P4W_cols', value_name='P4W_Response')

    # Trích xuất tên brand bằng Regex, rstrip('.1'), strip() và đưa về chữ thường để map ID
    .assign(
        Brand_Clean = lambda d: d['P4W_cols'].str.extract(brand_pattern)[0].str.strip().str.rstrip('.1'),
        Master_Id = lambda d: d['Brand_Clean'].astype(str).str.strip().str.lower().map(vlookup_dict)
    )

    # Lọc: Chỉ giữ lại các dòng phản hồi là 1 (Yes) và có Master_Id hợp lệ
    .query("P4W_Response == 1 and Master_Id.notna()")

    # Giữ các cột định danh quan trọng và loại bỏ dòng trùng lặp
    [['Serial number', 'Wave', 'Master_Id']]
    .drop_duplicates()
)


# --- 3. MERGE VÀ ĐÁNH DẤU FLAG VÀO BẢNG FACT_FUNNEL ---
# Sử dụng indicator=True để tự động kiểm tra xem dòng nào khớp thành công (match) giữa 2 bảng
fact_funnel = pd.merge(fact_funnel, df_P4W_flags, on=['Serial number', 'Wave', 'Master_Id'], how='left', indicator=True)

# Tạo cột flag chính thức dựa trên cột hệ thống '_merge' (Khớp thành công = 1, ngược lại = 0)
fact_funnel['P4W'] = (fact_funnel['_merge'] == 'both').astype(int)

# Xóa bỏ cột hệ thống '_merge' để giữ cho DataFrame sạch sẽ
fact_funnel = fact_funnel.drop(columns=['_merge'])


# --- 4. KIỂM TRA KẾT QUẢ ---
print(fact_funnel.info())
fact_funnel.head()

fact_funnel.to_csv('Fact Funnel.csv', index=False, encoding='utf-8-sig')

"""# Fact Brand Image

"""

qi_attributes = [
    'Những thương hiệu được ưa chuộng và phổ biến',
    'Bao bì có thiết kế thu hút',
    'Nhãn hiệu đáng tin cậy',
    'Giá cả hợp lý với chất lượng mang lại',
    'Phù hợp để thưởng thức hàng ngày',
    'Làm dịu cơn khát',
    'Vị ngon mà tôi yêu thích',
    'Thương hiệu mang tính hiện đại, trẻ trung',
    'Sản xuất từ nguyên liệu tự nhiên',
    'Mang đến sự vui tươi và lạc quan',
    'Có lợi cho sức khỏe',
    'Giúp giảm căng thẳng và mệt mỏi',
    'Mang lại cảm giác thư giãn',
    'Giải nhiệt cuộc sống',
    'Tạo cảm giác sảng khoái',
    'Tái tạo năng lượng',
    'Có nhiều vị để lựa chọn',
    'Mang đến cảm giác tươi mát',
    'DK/NA'
]

# Tìm tất cả các cột QI liên quan
qi_cols = []
for col in df_data.columns:
    if col.startswith('QI - '):
        for attr in qi_attributes:
            # Use regex to find the attribute at the end of the column name
            # The `re.escape(attr)` handles special characters in the attribute string
            if re.search(f'_{re.escape(attr)}$', col):
                qi_cols.append(col)
                break

# Unpivot (melt) các cột QI
df_qi_melted = df_data[['Serial number', 'Wave'] + qi_cols].melt(
    id_vars=['Serial number', 'Wave'],
    value_vars=qi_cols,
    var_name='QI_Column_Full_Name',
    value_name='Score'
)

# Convert Score to numeric, coercing errors to NaN
df_qi_melted['Score'] = pd.to_numeric(df_qi_melted['Score'], errors='coerce')

# Trích xuất Brand_Name_for_Vlookup và Attribute
def extract_brand_and_attribute(full_name):
    # Remove 'QI - ' prefix
    name_without_prefix = full_name.replace('QI - ', '', 1)

    for attr in qi_attributes:
        # Check if the attribute is at the end of the string
        if name_without_prefix.endswith(f'_{attr}'):
            brand_name = name_without_prefix.replace(f'_{attr}', '', 1)
            return brand_name, attr
    return None, None # Should not happen if qi_cols are correctly identified

# Apply the function to create new columns
df_qi_melted[['Brand_Name_for_Vlookup', 'Attribute']] = df_qi_melted['QI_Column_Full_Name'].apply(
    lambda x: pd.Series(extract_brand_and_attribute(x))
)

# Ánh xạ Brand_Name_for_Vlookup sang Master_Id
# Sử dụng vlookup_dict đã được tạo trước đó
df_qi_melted['Master_Id'] = df_qi_melted['Brand_Name_for_Vlookup'].str.lower().map(vlookup_dict)

# Khởi tạo fact_brand_image từ df_qi_melted sau khi đã có Master_Id
fact_brand_image = df_qi_melted.copy()

# Chọn và sắp xếp lại các cột theo yêu cầu
fact_brand_image = (
    df_qi_melted[['Serial number', 'Master_Id', 'Wave', 'Attribute', 'Score']]
    .groupby(['Serial number', 'Master_Id', 'Wave', 'Attribute'], as_index=False)
    .agg({'Score': 'max'})
)

# Chuyển đổi Master_Id và Score sang kiểu int
fact_brand_image['Master_Id'] = fact_brand_image['Master_Id'].astype(int)
# Fill NaN values in 'Score' with 0 before converting to int
fact_brand_image['Score'] = fact_brand_image['Score'].fillna(0).astype(int)

# Hiển thị kết quả
fact_brand_image

#fact_brand_image.to_csv('Fact Brand Image.csv', index=False, encoding='utf-8-sig')

"""#Fact Barriers"""

#1. Tìm tất cả các cột chứa thông tin Barrier (bắt đầu bằng QME2 -)
barrier_cols = [col for col in df_data.columns if col.startswith('QME2 -')]

# 2. Thực hiện Melt (Unpivot) bảng dữ liệu của bạn
df_barrier_melted = df_data[['Serial number', 'Wave'] + barrier_cols].melt(
    id_vars=['Serial number', 'Wave'],
    value_vars=barrier_cols,
    var_name='Raw_Barrier_Col',       # Cột tạm thời chứa chuỗi thô ban đầu
    value_name='Barrier_Response'     # Cột chứa câu trả lời (0/1)
)
df_barrier_melted

# Sử dụng Regex để bốc tách cấu trúc: QME2 - {Brand}_{Barrier}
pattern = r"QME2 - (.*?)_(.*)"

# Tiến hành tách làm 2 cột mới
df_barrier_melted[['Brand', 'Barrier']] = df_barrier_melted['Raw_Barrier_Col'].str.extract(pattern)

# Xem thử kết quả 5 dòng đầu
df_barrier_melted

import numpy as np

print('Tổng dòng trước dropna:', len(df_barrier_melted))
print('Số dòng NaN sẽ bị xoá:', df_barrier_melted['Barrier_Response'].isna().sum())
print('Số cột barrier tìm được:', len(barrier_cols))
print(barrier_cols[:20])

df_barrier_melted['Barrier_Response'] = df_barrier_melted['Barrier_Response'].replace(['#NULL!', 'None', 'Nan'], np.nan)

df_barrier_melted = df_barrier_melted.dropna(subset=['Barrier_Response'])
df_barrier_melted['Barrier_Response'] = df_barrier_melted['Barrier_Response'].astype(int)

df_barrier_melted

vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))

# Ensure the 'Brand' column is cleaned before mapping
df_barrier_melted['Master_Id'] = df_barrier_melted['Brand'].astype(str).str.strip().str.lower().map(vlookup_dict)

# Display the DataFrame with the new Master_Id column
df_barrier_melted

# Select and reorder columns for fact_barriers
fact_barriers = (
    df_barrier_melted[['Serial number', 'Wave', 'Master_Id', 'Barrier', 'Barrier_Response']]
    .groupby(['Serial number', 'Wave', 'Master_Id', 'Barrier'], as_index=False)
    .agg({'Barrier_Response': 'max'})
)
# Display the final fact_barriers DataFrame
fact_barriers.describe()

#fact_barriers.to_csv('Fact Barriers.csv', index=False, encoding='utf-8-sig')

"""#Fact Occasion"""

import pandas as pd
import numpy as np
import re

# Khởi tạo vlookup_dict chuẩn
vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))
if 'Master_Brand' in df_brand.columns:
    vlookup_dict.update(dict(zip(df_brand['Master_Brand'].str.lower(), df_brand['Master_Id'])))

# 1. Melt Q_TP3 columns
tp3_cols = [col for col in df_data.columns if col.startswith('Q_TP3_')]
df_tp3_melted = df_data[['Serial number', 'Wave'] + tp3_cols].melt(
    id_vars=['Serial number', 'Wave'],
    var_name='Raw_TP3_Col',
    value_name='Occasion_Response_Raw'
)

# 2. Trích xuất Brand từ tên cột và map sang Master_Id
def extract_brand_from_tp3_col(col_name):
    match = re.search(r"Q_TP3_R\d+-\s*(.*)", col_name)
    if match:
        return match.group(1).strip()
    return None

df_tp3_melted['Brand'] = df_tp3_melted['Raw_TP3_Col'].apply(extract_brand_from_tp3_col)
df_tp3_melted['Master_Id'] = df_tp3_melted['Brand'].astype(str).str.lower().map(vlookup_dict)

# Lọc bỏ các dòng không map được thương hiệu
df_tp3_melted = df_tp3_melted.dropna(subset=['Master_Id']).copy()
df_tp3_melted['Master_Id'] = df_tp3_melted['Master_Id'].astype(int)


# =========================================================================
# XỬ LÝ NULL VÀ CHUẨN HÓA DỮ LIỆU ĐẦU VÀO
# =========================================================================

df_tp3_melted['Occasion_Response_Raw'] = df_tp3_melted['Occasion_Response_Raw'].replace(['Nan', 'None', 'nan', '', 'NA'], np.nan)

df_tp3_melted['Occasion_Response_Clean'] = np.where(
    df_tp3_melted['Occasion_Response_Raw'].notna(),
    df_tp3_melted['Occasion_Response_Raw'].astype(str).str.strip(),
    np.nan
)

# Từ điển ánh xạ các dịp sử dụng tiếng Anh
occasion_mapping_dict = {
    'When outside': 'When outside',
    'When hanging out with friends/family': 'When hanging out with friends/family',
    'When having meals/party with friends/family': 'When having meals/party with friends/family',
    'When taking a break after school/work': 'When taking a break after school/work',
    'When having meals': 'When having meals',
    'When entertaining at home (Listen to music, watch movie, watch TV,...)': 'When entertaining at home (Listen to music, watch movie, watch TV,...)',
    'When watch movie/ attend music concert': 'When watch movie/ attend music concert',
    'After doing sport': 'After doing sport',
    'After consuming beer/ alcohol': 'After consuming beer/ alcohol'
}

# Chuẩn hoá dữ liệu thô: đưa dấu "…" về "...", để so khớp không phân biệt hoa/thường
df_tp3_melted['Occasion_Response_Clean'] = (
    df_tp3_melted['Occasion_Response_Clean']
    .str.replace('…', '...', regex=False)
)

# Map bằng key viết thường — CHỈ 1 LẦN DUY NHẤT, không có dòng map cũ nào khác phía sau nữa
occasion_mapping_dict_lower = {k.lower(): v for k, v in occasion_mapping_dict.items()}
df_tp3_melted['Mapped_Occasion'] = df_tp3_melted['Occasion_Response_Clean'].str.lower().map(occasion_mapping_dict_lower)

df_tp3_valid_responses = df_tp3_melted.dropna(subset=['Mapped_Occasion']).copy()

# 4. Tạo DataFrame phản hồi thực tế với Flag = 1
df_actual_responses = df_tp3_valid_responses[['Serial number', 'Wave', 'Master_Id', 'Mapped_Occasion']].drop_duplicates().copy()
df_actual_responses = df_actual_responses.rename(columns={'Mapped_Occasion': 'Occasion'})

df_actual_responses['Occasion'] = df_actual_responses['Occasion'].astype(str).str.lower().str.strip()
df_actual_responses['Flag'] = 1

# 5. Tạo bảng cơ sở phối hợp (Base Combinations)
unique_ids = df_tp3_valid_responses[['Serial number', 'Wave', 'Master_Id']].drop_duplicates().copy()

target_occasions_list = [str(occ).lower().strip() for occ in occasion_mapping_dict.values()]
target_occasions_df = pd.DataFrame({'Occasion': target_occasions_list})

unique_ids['key'] = 1
target_occasions_df['key'] = 1
fact_Occasion_all_combinations = pd.merge(unique_ids, target_occasions_df, on='key').drop(columns='key')

# 6. Merge dữ liệu để tạo bảng Fact Occasion hoàn chỉnh
fact_Occasion = pd.merge(
    fact_Occasion_all_combinations,
    df_actual_responses,
    on=['Serial number', 'Wave', 'Master_Id', 'Occasion'],
    how='left'
)
fact_Occasion['Flag'] = fact_Occasion['Flag'].fillna(0).astype(int)

fact_Occasion['Occasion'] = fact_Occasion['Occasion'].str.capitalize()

print(fact_Occasion.head(20))

fact_Occasion

#fact_Occasion.to_csv('Fact Occasion.csv', index=False, encoding='utf-8-sig')

"""# Fact Media Channe"""

#1. Tìm tất cả các cột chứa thông tin Barrier (bắt đầu bằng QME2 -)
Media_Channel = [col for col in df_data.columns if col.startswith('Q_TP1_')]

# 2. Thực hiện Melt (Unpivot) bảng dữ liệu của bạn
Media_Channel_melted = df_data[['Serial number', 'Wave'] + Media_Channel].melt(
    id_vars=['Serial number', 'Wave'],
    value_vars=Media_Channel,
    var_name='Raw_Media_Channel',       # Cột tạm thời chứa chuỗi thô ban đầu
    value_name='Media_Channel_Response'     # Cột chứa câu trả lời (0/1)
)
Media_Channel_melted

media_pattern = r".*?-\s*(.*?)_(.*)"

# 2. Tiến hành tách thành 2 cột mới: 'Brand' và 'Media Channel'
Media_Channel_melted[['Brand', 'Media Channel']] = Media_Channel_melted['Raw_Media_Channel'].str.extract(media_pattern)

# 3. Dọn dẹp dữ liệu: Thay thế <NA> hoặc các giá trị trống trong cột Response thành 0 như bước trước
Media_Channel_melted['Media_Channel_Response'] = Media_Channel_melted['Media_Channel_Response'].map({'1': 1, 1: 1}).fillna(0).astype(int)

# 4. Xóa cột chuỗi thô ban đầu cho sạch bảng
Media_Channel_melted = Media_Channel_melted.drop(columns=['Raw_Media_Channel'])

Media_Channel_melted

vlookup_dict = dict(zip(df_brand['Brand_Name'].str.lower(), df_brand['Master_Id']))

Media_Channel_melted['Master_Id'] = Media_Channel_melted['Brand'].astype(str).str.strip().str.lower().map(vlookup_dict)
Media_Channel_melted = Media_Channel_melted.drop(columns=['Brand'])

# ← THÊM bước gộp ở đây, trước khi export
Media_Channel_melted = (
    Media_Channel_melted
    .groupby(['Serial number', 'Wave', 'Master_Id', 'Media Channel'], as_index=False)
    .agg({'Media_Channel_Response': 'max'})
)

#Media_Channel_melted.to_csv('Fact Media Channel.csv', index=False, encoding='utf-8-sig')

"""#Fact Purchased Channel"""

# 1. Define mapping for Purchased Channels
purchased_channel_mapping = {
    'Siêu thị': 'Supermarket',
    'Supermarket': 'Supermarket',
    'Cửa hàng tạp hoá': 'Grocery Shop',
    'Grocery Shop': 'Grocery Shop',
    'Cửa hàng tiện lợi': 'Convenience store',
    'Convienient store': 'Convenience store', # Corrected spelling
    'Chợ': 'Market',
    'Market': 'Market',
    'Quán cà phê/quán nước bên đường': 'Coffee shop/ Beverage street vendor',
    'Coffee shop/ Beverage street vendor': 'Coffee shop/ Beverage street vendor',
    'Quán ăn/nhà hàng': 'Eatery place/restaurant',
    'Eatery place/restaurant': 'Eatery place/restaurant',
    'Căn-tin': 'Canteen',
    'Carteen': 'Canteen', # Corrected spelling
    'Các trang web bán hàng online': 'E-commerce website',
    'E-commerce website': 'E-commerce website',
    'Quầy bán hàng tự động': 'Vending machine',
    'Vending machine': 'Vending machine'
}

# 2. Identify Q_TP3 columns (these are the same columns used for Occasions, but here we interpret their VALUES as Purchased Channels)
tp3_cols = [col for col in df_data.columns if col.startswith('Q_TP3_')]

# 3. Melt df_data using Q_TP3 columns
df_purchased_melted = df_data[['Serial number', 'Wave'] + tp3_cols].melt(
    id_vars=['Serial number', 'Wave'],
    var_name='Raw_TP3_Col',
    value_name='Purchased_Channel_Response_Raw'
)

# 4. Extract Brand from Raw_TP3_Col and Map to Master_Id
def extract_brand_from_tp3_col(col_name):
    match = re.search(r"Q_TP3_R\d+-\s*(.*)", col_name)
    if match:
        return match.group(1).strip()
    return None

df_purchased_melted['Brand'] = df_purchased_melted['Raw_TP3_Col'].apply(extract_brand_from_tp3_col)
df_purchased_melted['Master_Id'] = df_purchased_melted['Brand'].astype(str).str.lower().map(vlookup_dict)

# Filter out rows where Master_Id could not be mapped (i.e., is NaN/None)
df_purchased_melted = df_purchased_melted.dropna(subset=['Master_Id']).copy()
df_purchased_melted['Master_Id'] = df_purchased_melted['Master_Id'].astype(int)

# 5. Clean and Map Purchased_Channel_Response_Raw to standardized names
df_purchased_melted['Purchased_Channel_Clean'] = (
    df_purchased_melted['Purchased_Channel_Response_Raw']
    .replace('Nan', pd.NA)
    .astype(str)
    .str.strip()
)
df_purchased_melted['Purchased_Channel_Clean'] = df_purchased_melted['Purchased_Channel_Clean'].replace('None', pd.NA)

# Map responses to standard channels, 'Other' for unmapped valid responses
df_purchased_melted['Mapped_Purchased_Channel'] = df_purchased_melted['Purchased_Channel_Clean'].map(purchased_channel_mapping).fillna(pd.NA)

# For valid but unmapped responses, assign 'Other'
other_responses_mask = (
    df_purchased_melted['Purchased_Channel_Clean'].notna() &
    ~df_purchased_melted['Purchased_Channel_Clean'].isin(purchased_channel_mapping.keys()) &
    df_purchased_melted['Mapped_Purchased_Channel'].isna() # Ensure it wasn't mapped by default
)
df_purchased_melted.loc[other_responses_mask, 'Mapped_Purchased_Channel'] = 'Other'

# Filter out rows where both Purchased_Channel_Clean and Mapped_Purchased_Channel are NA
df_purchased_melted_filtered = df_purchased_melted.dropna(subset=['Mapped_Purchased_Channel']).copy()

# 6. Create df_actual_responses with Flag = 1
df_actual_responses_channel = df_purchased_melted_filtered[[
    'Serial number', 'Wave', 'Master_Id', 'Mapped_Purchased_Channel'
]].drop_duplicates().copy()
df_actual_responses_channel['Respond'] = 1
df_actual_responses_channel = df_actual_responses_channel.rename(columns={'Mapped_Purchased_Channel': 'Purchased channel'})

# 7. Create a base DataFrame with all possible combinations of Serial number, Wave, Master_Id, and Purchased Channel
unique_ids_channel = df_purchased_melted[['Serial number', 'Wave', 'Master_Id']].drop_duplicates().copy()
target_channels_list = list(purchased_channel_mapping.values()) + ['Other']
target_channels_df = pd.DataFrame({'Purchased channel': target_channels_list}).drop_duplicates()

unique_ids_channel['key'] = 1
target_channels_df['key'] = 1
fact_Purchased_Channel_all_combinations = pd.merge(unique_ids_channel, target_channels_df, on='key').drop(columns='key')

# 8. Merge and Finalize fact_Purchased_Channel
fact_Purchased_Channel = pd.merge(
    fact_Purchased_Channel_all_combinations,
    df_actual_responses_channel,
    on=['Serial number', 'Wave', 'Master_Id', 'Purchased channel'],
    how='left'
)
fact_Purchased_Channel['Respond'] = fact_Purchased_Channel['Respond'].fillna(0).astype(int)

# Display the resulting DataFrame
print(fact_Purchased_Channel.info())

fact_Purchased_Channel

purchased_channel_mapping = {
    'Siêu thị': 'Supermarket', 'Cửa hàng tạp hoá': 'Grocery Shop', 'Cửa hàng tiện lợi': 'Convenience store',
    'Chợ': 'Market', 'Quán cà phê/quán nước bên đường': 'Coffee shop/ Beverage street vendor',
    'Quán ăn/nhà hàng': 'Eatery place/restaurant', 'Căn-tin': 'Canteen', 'Các trang web bán hàng online': 'E-commerce website',
    'Quầy bán hàng tự động': 'Vending machine',
    'Supermarket': 'Supermarket', 'Grocery Shop': 'Grocery Shop', 'Convenience store': 'Convenience store',
    'Convenient store': 'Convenience store', 'Convienient store': 'Convenience store', 'Market': 'Market',
    'Wet Markets': 'Market', 'Coffee shop/ Beverage street vendor': 'Coffee shop/ Beverage street vendor',
    'Eatery place/restaurant': 'Eatery place/restaurant', 'Canteen': 'Canteen', 'Carteen': 'Canteen',
    'E-commerce website': 'E-commerce website', 'Vending machine': 'Vending machine',
}

lowercase_purchased_channel_mapping = {k.lower(): v for k, v in purchased_channel_mapping.items()}

tp2_cols = [col for col in df_data.columns if col.startswith('Q_TP2_')]

def extract_brand(col_name):
    m = re.search(r'Q_TP2_R\d+-\s*(.*)', col_name)
    return m.group(1).strip() if m else None

df_melted = (
    df_data[['Serial number', 'Wave'] + tp2_cols]
    .melt(id_vars=['Serial number', 'Wave'], var_name='Raw_Col', value_name='Raw_Value')
    .assign(
        Brand=lambda d: d['Raw_Col'].apply(extract_brand),
        Master_Id=lambda d: d['Brand'].astype(str).str.lower().map(vlookup_dict)
    )
    .dropna(subset=['Master_Id'])
)
df_melted['Master_Id'] = df_melted['Master_Id'].astype(int)

df_melted['Value_Clean'] = (
    df_melted['Raw_Value']
    .replace({'Nan': pd.NA, 'None': pd.NA, '#NULL!': pd.NA})
    .astype(str)
    .str.strip()
    .replace('nan', pd.NA)
)

unmapped_values_check = df_melted[
    df_melted['Value_Clean'].notna() &
    ~df_melted['Value_Clean'].str.lower().isin(lowercase_purchased_channel_mapping.keys())
]['Value_Clean'].value_counts()

if not unmapped_values_check.empty:
    print("Unmapped values (add to mapping or will be dropped):")
    print(unmapped_values_check)
else:
    print("All values mapped successfully or are NA.")

df_melted['Purchased_Channel'] = (
    df_melted['Value_Clean'].str.lower()
    .map(lowercase_purchased_channel_mapping)
)

df_melted_filtered = df_melted.dropna(subset=['Purchased_Channel'])

df_actual = (
    df_melted_filtered[['Serial number', 'Wave', 'Master_Id', 'Purchased_Channel']]
    .drop_duplicates()
)
df_actual['Respond'] = 1
df_actual = df_actual.rename(columns={'Purchased_Channel': 'Purchased channel'})

unique_ids = df_melted[['Serial number', 'Wave', 'Master_Id']].drop_duplicates()
target_channels_list = list(set(purchased_channel_mapping.values()))
target_channels_df = pd.DataFrame({'Purchased channel': sorted(target_channels_list)})

unique_ids['_key'] = 1
target_channels_df['_key'] = 1
all_combinations = pd.merge(unique_ids, target_channels_df, on='_key').drop(columns='_key')

fact_Purchased_Channel = pd.merge(
    all_combinations,
    df_actual,
    on=['Serial number', 'Wave', 'Master_Id', 'Purchased channel'],
    how='left'
)
fact_Purchased_Channel['Respond'] = fact_Purchased_Channel['Respond'].fillna(0).astype(int)

fact_Purchased_Channel[fact_Purchased_Channel['Respond'] == 1]

fact_Purchased_Channel.to_csv('Fact Purchased Channel.csv', index=False, encoding='utf-8-sig')